require 'set'

MACOS_SYSTEM_LIBS = %w(
  /usr/lib/libMatch.1.dylib
  /usr/lib/libsysdiagnose.dylib
  /usr/lib/libxml2.2.dylib
  /usr/lib/libgermantok.dylib
  /usr/lib/libBSDPClient.A.dylib
  /usr/lib/libauto.dylib
  /usr/lib/libcoreroutine.dylib
  /usr/lib/libquit.dylib
  /usr/lib/libpmsample.dylib
  /usr/lib/libcupsimage.2.dylib
  /usr/lib/libipsec.A.dylib
  /usr/lib/libnetwork.dylib
  /usr/lib/libsasl2.2.dylib
  /usr/lib/libIASUnifiedProgress.dylib
  /usr/lib/libresolv.9.dylib
  /usr/lib/libcoretls.dylib
  /usr/lib/libdz.dylib
  /usr/lib/libnetsnmptrapd.25.dylib
  /usr/lib/libarchive.2.dylib
  /usr/lib/libgcc_s.10.5.dylib
  /usr/lib/libcupsmime.1.dylib
  /usr/lib/libtls.6.dylib
  /usr/lib/libXplugin.1.dylib
  /usr/lib/libxslt.1.dylib
  /usr/lib/libpcreposix.0.dylib
  /usr/lib/libOpenScriptingUtil.dylib
  /usr/lib/libFosl_dynamic.dylib
  /usr/lib/libcompression.dylib
  /usr/lib/libexslt.0.dylib
  /usr/lib/libcharset.1.dylib
  /usr/lib/libtailspin.dylib
  /usr/lib/libssl.0.9.8.dylib
  /usr/lib/libspindump.dylib
  /usr/lib/libktrace.dylib
  /usr/lib/libxar.1.dylib
  /usr/lib/libCRFSuite.dylib
  /usr/lib/libpcre.0.dylib
  /usr/lib/libapple_crypto.dylib
  /usr/lib/libnetsnmpagent.25.dylib
  /usr/lib/libATCommandStudioDynamic.dylib
  /usr/lib/libsystemstats.dylib
  /usr/lib/libruby.2.3.0.dylib
  /usr/lib/libnetsnmp.15.1.2.dylib
  /usr/lib/libecpg.6.5.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libcrypto.0.9.7.dylib
  /usr/lib/libsandbox.1.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libiodbc.2.1.18.dylib
  /usr/lib/libiodbcinst.2.1.18.dylib
  /usr/lib/libdtrace.dylib
  /usr/lib/libChineseTokenizer.dylib
  /usr/lib/liblangid.dylib
  /usr/lib/libnetsnmp.25.dylib
  /usr/lib/libcmph.dylib
  /usr/lib/libmecab.1.0.0.dylib
  /usr/lib/libcups.2.dylib
  /usr/lib/libssl.35.dylib
  /usr/lib/libtzupdate.dylib
  /usr/lib/libtls.15.dylib
  /usr/lib/libpanel.5.4.dylib
  /usr/lib/libcsfde.dylib
  /usr/lib/PN548_HAL_OSX.dylib
  /usr/lib/libMaxEnt.dylib
  /usr/lib/libstdc++.6.0.9.dylib
  /usr/lib/libheimdal-asn1.dylib
  /usr/lib/PN548_API.dylib
  /usr/lib/libmecabra.dylib
  /usr/lib/libcrypto.41.dylib
  /usr/lib/libDiagnosticMessagesClient.dylib
  /usr/lib/libTelephonyUtilDynamic.dylib
  /usr/lib/libcrypto.35.dylib
  /usr/lib/libssl.0.9.7.dylib
  /usr/lib/libSystem.B.dylib
  /usr/lib/libform.5.4.dylib
  /usr/lib/libedit.3.dylib
  /usr/lib/PN548_OSX.dylib
  /usr/lib/libParallelCompression.dylib
  /usr/lib/libnetworkextension.dylib
  /usr/lib/libssl.43.dylib
  /usr/lib/libbsm.0.dylib
  /usr/lib/libFDR_osx.dylib
  /usr/lib/libcupsppdc.1.dylib
  /usr/lib/libmarisa.dylib
  /usr/lib/libdscsym.dylib
  /usr/lib/libAudioIssueDetector.dylib
  /usr/lib/libThaiTokenizer.dylib
  /usr/lib/libodmodule.dylib
  /usr/lib/libXSEvent.dylib
  /usr/lib/libsysmon.dylib
  /usr/lib/libate.dylib
  /usr/lib/libScreenReader.dylib
  /usr/lib/libgmalloc.dylib
  /usr/lib/libpq.5.6.dylib
  /usr/lib/libecpg_compat.3.5.dylib
  /usr/lib/libQMIParserDynamic.dylib
  /usr/lib/libffi.dylib
  /usr/lib/libCoreStorage.dylib
  /usr/lib/libboringssl.dylib
  /usr/lib/libnfrestore.dylib
  /usr/lib/libSMC.dylib
  /usr/lib/libcurl.4.dylib
  /usr/lib/libusrtcp.dylib
  /usr/lib/libodfde.dylib
  /usr/lib/libpam.2.dylib
  /usr/lib/libobjc.A.dylib
  /usr/lib/libxcselect.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libutil.dylib
  /usr/lib/liblzma.5.dylib
  /usr/lib/libtidy.A.dylib
  /usr/lib/libnetsnmphelpers.25.dylib
  /usr/lib/libprequelite.dylib
  /usr/lib/libipconfig.dylib
  /usr/lib/libc++abi.dylib
  /usr/lib/libsqlite3.dylib
  /usr/lib/libicucore.A.dylib
  /usr/lib/libnetsnmpmibs.25.dylib
  /usr/lib/libeasyperf.dylib
  /usr/lib/libIASAuthReboot.dylib
  /usr/lib/libpmenergy.dylib
  /usr/lib/libdns_services.dylib
  /usr/lib/libexpat.1.dylib
  /usr/lib/libhunspell-1.2.0.0.0.dylib
  /usr/lib/ssh-keychain.dylib
  /usr/lib/libnetsnmp.5.2.1.dylib
  /usr/lib/libapple_nghttp2.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libAccountPolicyTranslation.dylib
  /usr/lib/libmenu.5.4.dylib
  /usr/lib/libpgtypes.3.4.dylib
  /usr/lib/libz.1.dylib
  /usr/lib/libaprutil-1.0.dylib
  /usr/lib/libcrypto.0.9.8.dylib
  /usr/lib/libpcap.A.dylib
  /usr/lib/libUniversalAccess.dylib
  /usr/lib/libenergytrace.dylib
  /usr/lib/libDHCPServer.A.dylib
  /usr/lib/libcoretls_cfhelpers.dylib
  /usr/lib/libpam.1.dylib
  /usr/lib/libcupscgi.1.dylib
  /usr/lib/libapr-1.0.dylib
  /usr/lib/libnfshared.dylib
  /usr/lib/libauditd.0.dylib
).to_set
