# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Added at 2018-03-13 10:01:45 -0400 by smashwilson:
gem "octokit", "~> 4.8"
